plugins {
    id 'com.android.application'
}

android {
    namespace 'br.grassinimoraes.divasteroides'
    compileSdk 33

    defaultConfig {
        applicationId 'br.grassinimoraes.divasteroides'
        minSdk 8
        targetSdk 28
        versionCode 1
        versionName '1.0'
    }

    sourceSets {
        main {
            manifest.srcFile 'src/main/AndroidManifest.xml'
            java.srcDirs = [
                    '../src',
                    '../third_party/AndEngine/src',
                    '../third_party/AndEnginePhysicsBox2DExtension/src'
            ]
            assets.srcDirs = ['../assets']
            jniLibs.srcDirs = [
                    '../third_party/AndEngine/libs',
                    '../third_party/AndEnginePhysicsBox2DExtension/libs'
            ]
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
