name: Android build

on:
  push:
    branches: [ main, configura-build-gradle ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '7.5.1'

      - run: gradle testDebugUnitTest assembleDebug --stacktrace
